// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbSYT06xpyqHQj7qhlU9P9FpegtVKJ9tk',
    appId: '1:938598789953:web:5974ab49716d85681067c0',
    messagingSenderId: '938598789953',
    projectId: 'wiphuproject',
    authDomain: 'wiphuproject.firebaseapp.com',
    storageBucket: 'wiphuproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWVhJfQLF0egIMN1eEzwuXuQQdHHGxEk',
    appId: '1:938598789953:android:eee1d0906050e70b1067c0',
    messagingSenderId: '938598789953',
    projectId: 'wiphuproject',
    storageBucket: 'wiphuproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHS02deYFbLc1y3lLiO_nNrMTzKFYMbPo',
    appId: '1:938598789953:ios:93abbdb438984f6b1067c0',
    messagingSenderId: '938598789953',
    projectId: 'wiphuproject',
    storageBucket: 'wiphuproject.appspot.com',
    iosBundleId: 'com.ats.wiphuproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHS02deYFbLc1y3lLiO_nNrMTzKFYMbPo',
    appId: '1:938598789953:ios:93abbdb438984f6b1067c0',
    messagingSenderId: '938598789953',
    projectId: 'wiphuproject',
    storageBucket: 'wiphuproject.appspot.com',
    iosBundleId: 'com.ats.wiphuproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbSYT06xpyqHQj7qhlU9P9FpegtVKJ9tk',
    appId: '1:938598789953:web:048d80a3b5dac2031067c0',
    messagingSenderId: '938598789953',
    projectId: 'wiphuproject',
    authDomain: 'wiphuproject.firebaseapp.com',
    storageBucket: 'wiphuproject.appspot.com',
  );
}
